package uk.gov.homeoffice.cts.model;


public interface DeadlineConfiguration {

    //DCU
    Integer DCU_MINISTERIAL_CASE_RESPONSE_DEADLINE = 15;
    Integer DCU_MINISTERIAL_ALLOCATE_TARGET = 2;
    Integer DCU_MINISTERIAL_DRAFT_RESPONSE_TARGET = 10;
    Integer DCU_MINISTERIAL_PO_TARGET = 11;
    Integer DCU_MINISTERIAL_DISPATCH_TARGET = 15;


    Integer DCU_TREAT_OFFICIAL_CASE_RESPONSE_DEADLINE = 20;

    //FOI

    Integer FOI_CASE_RESPONSE_DEADLINE = 20;
    Integer FOI_ALLOCATE_TARGET = 2;
    Integer FOI_DRAFT_RESPONSE_TARGET = 15;
    Integer FOI_SCS_APPROVAL_TARGET = 17;

    Integer FOI_FSC_CASE_RESPONSE_DEADLINE = 20;
    Integer FOI_FTC_CASE_RESPONSE_DEADLINE = 5;

    //HMPO collective
    Integer HMPO_COLLECTIVES_CASE_RESPONSE_DEADLINE = -10;

    //HMPO complaints
    Integer HMPO_STAGE_1_CASE_RESPONSE_DEADLINE = 10;
    Integer HMPO_DIRECT_GENRAL_CASE_RESPONSE_DEADLINE = 2;
    Integer HMPO_GNR_CASE_RESPONSE_DEADLINE = 10;
    Integer HMPO_COMPLAINTS_DEFER_CASE_RESPONSE_DEADLINE = 6;

    //UKVI
    //UKVI_B_REF and UKVI_M_REF
    Integer UKVI_B_M_REF_CASE_RESPONSE_DEADLINE = 20;
    Integer UKVI_B_M_REF_ALLOCATE_TO_RESPONDER_TARGET = 2;
    Integer UKVI_B_M_REF_RESPONDER_HUB_TARGET = 2;

    //UKVI_B_REF
    Integer UKVI_B_REF_DRAFT_RESPONSE_TARGET = 12;

    //UKVI_M_REF
    Integer UKVI_M_REF_DRAFT_RESPONSE_TARGET = 10;


}
